### ISSUE TITLE
isCustomDate: missing.old version of  daterangepicker.js

### ISSUE THREAD

**Issue by vdvb** [kartik-v/yii2-date-range#100]
I am missing the isCustomDate option, i think it could be a version problem.
i installed this plug-in accordingly to
$ php composer.phar require kartik-v/yii2-date-range "dev-master"
the version installed is
* @version: 2.1.19

the latest version on his(dangrossman) site is
@version: 2.1.25

How can i resolve this
Thx.
B

**Comment by kartik-v** [comment]
The latest release is v3.0.3 of the source plugin. Update your code as per that.
