### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thiagotalma** [kartik-v/yii2-date-range#103]
Is it time to release a new stable release?
The last one has already completed 1 year of age  :-)

**Comment by kartik-v** [comment]
[Done](https://github.com/kartik-v/yii2-date-range/releases/tag/1.6.8).

**Comment by thiagotalma** [comment]
Thanks @kartik-v !

You could consider releasing a version for your other extensions that are already stable.

It would be great to be able to use your extensions with `"minimum-stability": "stable"` but today there are some versions far behind dev.
