### ISSUE TITLE
Undefined class DateRangePicker

### ISSUE THREAD

**Issue by Alek2012** [kartik-v/yii2-date-range#105]
Hi Kartik, after installation I can't correctly use kartik\daterange\DateRangePicker in Yii2 advanced 2.0.12 version. Undefined class DateRangePicker. My composer.json - "kartik-v/yii2-date-range": "*"
Thks in advance.

**Comment by kartik-v** [comment]
Seems an incorrect install on your environment - try to reinstall your composer packages.
