### ISSUE TITLE
How do I hide the default values for an input field when I use it as a filter?

### ISSUE THREAD

**Issue by makaronnik** [kartik-v/yii2-date-range#106]
Hi Kartik!
I use this widget as a filter for GridView.
Until the last update, the empty filter field looked like this:
![1](https://user-images.githubusercontent.com/9981799/29770673-d1fe5562-8bf8-11e7-8855-5c9cabdcc677.PNG)
After upgrading to v1.6.8, it looks like this:
![2](https://user-images.githubusercontent.com/9981799/29770700-f4e51f8e-8bf8-11e7-8e84-e505e52cfa50.PNG)
How to fix it?

**Comment by markmarco16** [comment]
hello, i have same problem, you can fix this?

**Comment by kartik-v** [comment]
You are using with `presetDropdown` option set to `true`... with this set to `true` you cannot have NULL values (NULL actually means today). Relates to #88.

- either use with `presetDropdown` set to `false`... OR
- or with `presetDropdown` set to `true`... configure and style your html markup correctly

Am open to suggestions to improve.

**Comment by kartik-v** [comment]
You have an option to hide or style the default value.

Set `DateRangePicker::defaultPresetValueOptions` to style the default value.

For example to hide the default preset value:

```php
'defaultPresetValueOptions' => ['style'=>'display:none']
```

This should achieve your use case of showing a blank display...

**Comment by kartik-v** [comment]
You have an option to hide or style the default value.

Set `DateRangePicker::defaultPresetValueOptions` to style the default value.

For example to hide the default preset value (and show a blank display like earlier releases):

```php
'defaultPresetValueOptions' => ['style'=>'display:none']
```

or style it better to fit the container ... e.g.

```php
'defaultPresetValueOptions' => [
    'tag'=>'span', 
    'style'=>'display:inline-block;width:40px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis'
]
```
This should achieve your use case of showing a blank display. So closing this issue, and will open it again if there is anything better suggested.

**Comment by markmarco16** [comment]
Thanks! This work for me

**Comment by makaronnik** [comment]
I, apparently, incorrectly formulated the problem.
Your component has a "hideInput" parameter.
Previously, it gave an effect, even when the "presetDropdown" parameter was set to "true".
Now, with "presetDropdown" enabled, the "hideInput" parameter has no effect.

**Comment by kartik-v** [comment]
Yes with the last release to avoid the logical error... Preset drop-down will always be shown without input...

**Comment by makaronnik** [comment]
Will this behavior be changed in the next releases?

**Comment by kartik-v** [comment]
Not sure if there is any alternative.

This is a source plugin specific issue... refer the example with [preset dropdown at the plugin site](http://www.daterangepicker.com/#ex4) ... it does not allow to edit the input directly.

When using preset dropdowns... the plugin works in a way where you just cannot enter a empty value... hence the input has to be hidden.
