### ISSUE TITLE
Pjax doesn't reinit the date range component

### ISSUE THREAD

**Issue by darkrift** [kartik-v/yii2-date-range#109]
My issue is similar to #48

I have a div container that I'm refreshing with pjax and the daterange component is in the header of that container to filter the gridview displayed on that page. Essentially the idea is that when we change the search fields (which aren't tied directly to gridview), we submit the form to filter it through pjax and update the container.

When the new html is rendered the daterange is not configured properly. It is displayed but clicking on the "range-value" field doesn't open the container to display the calendars as if it wasn't initialized.

I was able to make it 99% functionnal by setting the pjaxContainerId field. When the pjax request is done, the component is now reconfigured and opens on the second load. 

Using pjaxContainerId however leads to a few glitches :
1. The start and end calendars selection shown in the container is set back to the initial values of the very first page load. 
2. if I open the container and click on apply without changing the values in the calendars, the sent values are the one from the last selection instead of being what is shown (which are the original values described in point 1). The displayed date is correct in the "range-value" span.

I'm thinking that the underlying problem is the same as #48 though.

Any idea what could be wrong or a time frame when you could fix the issue ?

**Comment by kartik-v** [comment]
You can set `pjaxContainerId` property of the DateRangePicker widget to the Pjax container options id enclosing.
