### ISSUE TITLE
current day in single mod

### ISSUE THREAD

**Issue by kzpromo** [kartik-v/yii2-date-range#110]
hello, i have some troubles with DateRangePicker in single mod
when i'm trying to select the current day, it doesn't paste date into the filter field
```
[
    'attribute' => 'created_at',
    'filter' => DateRangePicker::widget([
    'model' => $searchModel,
    'attribute' => 'created_at',
    'convertFormat' => true,
    'pluginOptions' => [
          'singleDatePicker'=>true,
          'locale' => [
                'format' => 'Y-m-d'
                 ],
           ],
       ]),
       'value' => function($data){
              return $data->created_at;
        }
 ],
```
sorry for my english ;)

**Comment by ZxcR** [comment]
I have the same trouble. Did you find solution?

**Comment by s1lver** [comment]
I confirm the problem. It is observed not only in single, but also in the choice of the date range. The first value does not work when first selected. If you select any other, the selection of the first value starts to work.
