### ISSUE TITLE
startAttribute and endAttribute values not assigned

### ISSUE THREAD

**Issue by madisx** [kartik-v/yii2-date-range#119]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-date-range.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/date-range) and [demos](http://demos.krajee.com/date-range-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create widget with startAttribute and endAttribute - creates hidden inputs for start and end date - on demo page Hidden Start & End (Without model # 1)
2. Select any date range

## Expected behavior and actual behavior

When I follow those steps, first time after page reload, selecting the date range startAttribute input and endAttribute input values are set to empty. The range input itself has the correct value.
```
<input type="hidden" id="w0" class="form-control" name="report_date_range" data-krajee-daterangepicker="daterangepicker_d6a27154" value="2018-04-01 - 2018-04-30">
<input type="hidden" id="w0-start" name="from_date" value="">
<input type="hidden" id="w0-end" name="to_date" value="">
```

I was expecting start and end date inputs populated with values selected.

I have tested different combinations of properties, but as soon as startAttribute and endAttribute are set this behavior presents itself.

## (Possible) cause and solution

Default callback generated by DateRangePicker.php function registerAssets is 

```
function(start,end,label){
    var val=start.format('YYYY-MM-DD') + ' - ' + end.format('YYYY-MM-DD');
    var v=jQuery('#w0').val() ? start.format('YYYY-MM-DD') : ''; //jQuery('#w0').val() is not set at this point so v==''
    jQuery('#w0-start').val(v).trigger('change');
    var v=jQuery('#w0').val() ? end.format('YYYY-MM-DD') : '';
    jQuery('#w0-end').val(v).trigger('change');
    jQuery("#w0").val(val).trigger('change'); //jQuery('#w0').val() != ""
}
```
But the jQuery('#w0').val() is empty when it is used for assigning the var v on lines 3 and 5 of the function while the date range is being selected for the first time.

Changing the order of rows in that function resulted in expected behavior. This can be achieved changing (Line 273 in current revision) from 
```
$change = $rangeJs . "{$input}.val(val).trigger('change');";
```
to

```
$change = "{$input}.val(val).trigger('change');" . $rangeJs;
```
This causes the hidden input for the range be assigned a value before it is used in the condition for start and end inputs. Resulting in callback function:
```
function(start,end,label){
    var val=start.format('YYYY-MM-DD') + ' - ' + end.format('YYYY-MM-DD');
    jQuery("#w0").val(val).trigger('change');
    var v=jQuery('#w0').val() ? start.format('YYYY-MM-DD') : '';
    jQuery('#w0-start').val(v).trigger('change');
    var v=jQuery('#w0').val() ? end.format('YYYY-MM-DD') : '';
    jQuery('#w0-end').val(v).trigger('change');    
}
```

After the modification no unexpected behavior has been detected so far.
#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-date-range version: 1.6.9

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/date-range-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-date-range without other plugins.

**Comment by ejoful** [comment]
666 good

**Comment by ejoful** [comment]
good job

**Comment by chenshuiluke** [comment]
Same issue here
