### ISSUE TITLE
Trait 'kartik\base\BootstrapTrait' not found

### ISSUE THREAD

**Issue by micaelomota** [kartik-v/yii2-date-range#123]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-date-range.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/date-range) and [demos](http://demos.krajee.com/date-range-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install using php composer.phar require kartik-v/yii2-date-range "*"
2. Try the first example in http://demos.krajee.com/date-range#usage
3. Open the screen with daterange and get the error

## Expected behavior and actual behavior

When I follow those steps, I see...

yii\base\ErrorException: Trait 'kartik\base\BootstrapTrait' not found in /var/www/html/sct/vendor/kartik-v/yii2-widget-activeform/src/ActiveForm.php:49
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
Copy Stacktrace Search Stackoverflow Search Google Error
PHP Fatal Error – yii\base\ErrorException
Trait 'kartik\base\BootstrapTrait' not found

I was expecting...
The screen running as in the example
## Environment
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-06-07T19:43:03
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-date-range version: v1.6.9

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/date-range-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-date-range without other plugins.

**Comment by kartik-v** [comment]
Update your packages via composer. You do not have the latest release of  yii2-krajee-base.
