### ISSUE TITLE
Add Czech Translations

### ISSUE THREAD

**Issue by archaoncz** [kartik-v/yii2-date-range#125]
`return [
    'Apply' => 'Použít',
    'Cancel' => 'Zrušit',
    'Custom Range' => 'Zadat rozmezí',
    'From' => 'Od',
    'Last Month' => 'Minulý měsíc',
    'Last {n} Days' => 'Posledních {n} dní',
    'Select Date Range' => 'Vyberte časové rozmezí,
    'This Month' => 'Tento měsíc',
    'To' => 'Do',
    'Today' => 'Dnes',
    'W' => 'W',
    'Yesterday' => 'Včera',
];
`

**Comment by kartik-v** [comment]
Thanks - can you please submit a PR?
