### ISSUE TITLE
Not working with jquery 3.*

### ISSUE THREAD

**Issue by loveorigami** [kartik-v/yii2-date-range#127]
This plugin not working with  jquery 3.*

**Comment by amankograver** [comment]
@loveorigami hi, do you have problems with mark up?

**Comment by amankograver** [comment]
@loveorigami i'm use jquery 3.2.1, but with this option in composer.json it works:
"kartik-v/yii2-date-range": "v1.6.6"
if i use it "kartik-v/yii2-date-range": "dev-master" i have problems with mark up without js errors

**Comment by loveorigami** [comment]
Yes, I use "kartik-v/yii2-date-range": "dev-master"
and widget work fine with jquery 2.2

![002](https://user-images.githubusercontent.com/98164/44569997-eab43380-a784-11e8-8848-8afe17d970a6.jpg)

And not displayed in jquery 3.

![003](https://user-images.githubusercontent.com/98164/44570016-015a8a80-a785-11e8-871b-d1b8fdd083a5.jpg)

Thanks, I am trying your solutions

**Comment by amankograver** [comment]
@loveorigami so wait for vendors answer

**Comment by kartik-v** [comment]
Not sure can reproduce. The [docs and demos pages](http://demos.krajee.com/date-range) does run on jQuery 3.x.

**Comment by loveorigami** [comment]
How version yii2-date-range?
@amankograver wrote

> "kartik-v/yii2-date-range": "v1.6.6"
if i use it "kartik-v/yii2-date-range": "dev-master" i have problems with mark up without js errors

**Comment by loveorigami** [comment]
I am now update with v. 1.7.0 - not worked!
