### ISSUE TITLE
The first value in the list of predefined dates is not filled

### ISSUE THREAD

**Issue by s1lver** [kartik-v/yii2-date-range#130]
**Problem**

When you first open the list of preset dates, the default is "Today". But when you try to select "Today", this option does not apply. After selecting any other option, the "Today" item is applied normally. A similar situation with any other date set by default.

I have not found the option to change this behavior.

![default](https://user-images.githubusercontent.com/4567634/45419354-c49cf780-b68f-11e8-849d-4aa38165b220.png)

![default](https://user-images.githubusercontent.com/4567634/45422271-6c1e2800-b698-11e8-8725-7ec2cbed32c5.png)

When clicking, the value is not set.

My config:
```php
[
'filterType' => GridView::FILTER_DATE_RANGE,
'filterWidgetOptions' => [
	'options' => [
		style' => 'cursor:pointer;'
	],
        'pluginOptions' => [
	       'locale' => [
		'format' => 'DD.MM.YYYY',
		'separator' => ' по '
	],
	'allowClear' => true,
	'autoclose' => true,
	'format' => 'DD.MM.YYYY',
	'separator' => ' по '
],
'presetDropdown' => true
],
'attribute' => 'create_date',
'value' => 'create_date',
'options' => ['width' => '240px']
]

```

I've prepared a solution to change this behavior, but I would like to ask first. Perhaps there is some option that changes this behavior, but I did not find it?

#### Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: v3.2.1
- yii2-date-range version: e1829cf

**Comment by raflyazf** [comment]
did you already found the solution?
I got same problem

**Comment by uagrace** [comment]
v1.6.7 works fine

**Comment by kartik-v** [comment]
Use v1.7.1 - this should have been resolved.
