### ISSUE TITLE
DateRangePicker has problems with BootstrapAsset

### ISSUE THREAD

**Issue by pogromistik** [kartik-v/yii2-date-range#133]
After init DateRangePicker i has exception "An asset bundle that depends on 'yii\bootstrap\BootstrapAsset' has a higher javascript file position configured than 'yii\bootstrap\BootstrapAsset'".

If delete $this->initBsAssets(); from yii2-krajee-base/src/AssetBundle.php, the problem will be solved.

**Comment by kartik-v** [comment]
The extension depends on `yii\bootstrap\BootstrapAsset` - check if any of your code or other asset bundles is forcing the `yii\bootstrap\BootstrapAsset` to be loaded differently causing the dependency to fail.
