### ISSUE TITLE
How disabled DateRangePicker ?

### ISSUE THREAD

**Issue by xzibit26099** [kartik-v/yii2-date-range#136]
Hello! There was a task to make the disabled field in certain situations, but it is impossible to do it.
Here's the code:
http://i.imgur.com/cunqVOU.png
http://i.imgur.com/OpAxiZl.png

Is this bug?
If so, when can you fix it)
Or am I doing something wrong?)

**Comment by kartik-v** [comment]
It should work with disabled and readonly properties ... check [the usage examples](http://demos.krajee.com/date-range#usage).
