### ISSUE TITLE
daterange.js firstDayOfWeek is not a function

### ISSUE THREAD

**Issue by MaGiCmAsTeR0511** [kartik-v/yii2-date-range#140]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x ] The issue still exists against the latest `master` branch of yii2-date-range.
- [x ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/date-range) and [demos](http://demos.krajee.com/date-range-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [x ] I have included a failing test as a pull request (Optional).

#### Browsers

- [ x] Google Chrome
- [x ] Mozilla Firefox
- [x ] Internet Explorer
- [x ] Safari

#### Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-date-range version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/date-range-demo)
- [x ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-date-range without other plugins.

when i use the Daterangepicker following error is shown

jquery.js:3869 Uncaught TypeError: moment.localeData.firstDayOfWeek is not a function

it is in the 86 line of your daterangejs

when i delete this line everything is  working fine, this is also my workaround till today but with every composer update this error is shown again 

can you please fix that

**Comment by kartik-v** [comment]
This is related to the [third party date range picker plugin](https://github.com/dangrossman/daterangepicker). 

Ideally you should not be facing this issue (as can be seen in the demos). However, if you feel there is some issue that needs to be resolved - please report it to the above plugin author - so that it can be reflected here.
