### ISSUE TITLE
Array indexes don't work on the attribute

### ISSUE THREAD

**Issue by kevm256** [kartik-v/yii2-date-range#142]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of yii2-date-range.
- [ x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/date-range) and [demos](http://demos.krajee.com/date-range-demo).
- [ x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Load the following view:

```
<?php

use kartik\daterange\DateRangePicker;
use yii\base\Model;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

class TestModel extends Model
{
    public $start;
    public $end;
}
$models = [];
$models[0] = new TestModel([
    'start' => '2019-01-01',
    'end' => '2019-01-01']);
$models[1] = new TestModel();

Model::loadMultiple($models, Yii::$app->request->post());

$form = ActiveForm::begin();

foreach($models as $id=>$model)
{
    echo $form->field($model, "[$id]start")->widget(
            DateRangePicker::class,
    [
        'model' => $model,
        'startAttribute' => "[$id]start",
        'endAttribute' => "[$id]end",
        'convertFormat'=>true,
        'pluginOptions'=>[
            'locale'=>['format'=>'Y-m-d H:i:s'],
        ],
    ]);
}
echo Html::submitButton();
ActiveForm::end();
```

## Expected behavior and actual behavior

When I follow those steps, I see...
A Yii PHP Error message:

Unknown Property – yii\base\UnknownPropertyException

Setting unknown property: TestModel::[0]start

I was expecting...
To see a form with data rang `pickers`

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [X ] Safari

#### Operating System

- [ ] Windows
- [X ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-date-range version: 

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/date-range-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-date-range without other plugins.

**Comment by kartik-v** [comment]
Thanks - Resolved via your PR #143
