### ISSUE TITLE
Correct date range preset dropdown selection for Today

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-date-range#148]
In preset dropdown, when value is null, **Today** is by default selected - but one cannot select today until one changes to some other value. Correct this capability through additional scripting specifically for preset dropdown.

**Comment by FreekGille** [comment]
@kartik-v Thanks for the amazing work on all your extensions. I noticed that the scenario with "Today" as you've described above is still not working. On your own website (https://demos.krajee.com/date-range#usage), the third example has "Today" selected by default and can't be selected until a different date is selected first.
