### ISSUE TITLE
I don't know how the language displays

### ISSUE THREAD

**Issue by zizhuxuaner** [kartik-v/yii2-date-range#151]
I don't know how the language displays

**Comment by zizhuxuaner** [comment]
请问一下，如何才能默认显示中文，我的common\config\main.php 设置 'language'=>'zh-CN', 但是并没有显示对应的语言，只有这个插件是这样子的。

**Comment by zizhuxuaner** [comment]
The reason is found. When inheritance is used, the resource location of the language pack is incorrect.

**Comment by empytree** [comment]
The problem persists. When you use class extended from the widget, language asset for Moment fails to register. I believe the problem is linked with that line: https://github.com/kartik-v/yii2-date-range/blob/master/src/DateRangePicker.php#L388
