### ISSUE TITLE
Bad positiong for elements in BS3 version

### ISSUE THREAD

**Issue by evgenyvolferts** [kartik-v/yii2-date-range#153]
![image](https://user-images.githubusercontent.com/26716666/81684824-fb787180-945f-11ea-9ba4-f01b71d510dc.png)

Pull request #149 will fix this issue

**Comment by kartik-v** [comment]
I think - will need to include separate styling for BS3 and BS4.... will check this when I get time.

**Comment by CyanoFresh** [comment]
any update on this

**Comment by turboezh** [comment]
Hi, @kartik-v. This is still an issue, even here https://demos.krajee.com/bs3/date-range. Could you please fix it?
