### ISSUE TITLE
Date does not populate if you choose start and end both today

### ISSUE THREAD

**Issue by AlanHeckinJohnston** [kartik-v/yii2-date-range#158]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-date-range.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/date-range) and [demos](http://demos.krajee.com/date-range-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a standard date range picker.
2. Select the start date to be today.
3. Select end date to be today.
4. Press apply.

## Expected behavior and actual behavior
Date range should populate. It does not populate. However, if there was already a date populated, it does populate.

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-date-range version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/date-range-demo) ( does not occur because it is already populated, and the bug doesn't occur this way)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-date-range without other plugins.

**Comment by FreekGille** [comment]
I've noticed this bug too and it appears on demo 3 on the demos page (https://demos.krajee.com/date-range#usage) as well.. Hope this gets fixed soon.
