### ISSUE TITLE
minDate and maxDate pluginOptions not working

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-date-range#21]
I'm trying to get the minDate and maxDate pluginOptions to work to limit the times the user is able to select. I would like the user to be able to select and time between now and 14 days in the future. Here is my code:

<?= $form->field($model, 'daterange', [
        'addon'=>['prepend'=>['content'=>'<i class="glyphicon glyphicon-calendar"></i>']],
        'options'=>['class'=>'drp-container form-group']
        ])->widget(DateRangePicker::classname(), [
            'useWithAddon'=>true,
            'convertFormat' => true,
            'pluginOptions' => [
                'timePicker' => true,
                'timePickerIncrement' => 15,
                'timePicker12Hour' => false,
                'separator' => ' to ',
                'minDate' => 'moment()',
                'maxDate' => "moment().startOf('day').add(14,'days')",
                'format' => 'Y-m-d h:i A']
        ]);
    ?>

Without the 'minDate' and 'maxDate' options, everything works, with them on, I cannot select any days and can only go back into the past.

**Comment by fedemotta** [comment]
I think you need to use [JsExpression](http://www.yiiframework.com/doc-2.0/yii-web-jsexpression.html) to be recognized as js code. Anyway, it is better (and easy) to use the [PHP date function](http://php.net/manual/es/function.date.php).

**Comment by kartik-v** [comment]
Yes javascript expressions / methods cannot be passed just as a string... they need to be passed with JsExpression as @fedemotta mentioned.
