### ISSUE TITLE
yii.js data-method action not working on plugin load

### ISSUE THREAD

**Issue by manquer** [kartik-v/yii2-date-range#24]
On loading plugin the yii.js data-method listeners no longer work.
in DateRangerPickerAsset, on setting up js/daterangepicker asset, the yii.js action fails

     public function init()
      {
           $this->setSourcePath(__DIR__ . '/assets');
           $this->setupAssets('css', ['css/daterangepicker', 'css/daterangepicker-kv']);
           $this->setupAssets('js', ['js/daterangepicker']);
           parent::init();
       }

**Comment by kartik-v** [comment]
Cannot reproduce this. You may need to check your application code / config for other javascript errors. If you do find a reproducible example please share so that this can be opened.
