### ISSUE TITLE
Moment.js and other assets move to @bower folder

### ISSUE THREAD

**Issue by githubjeka** [kartik-v/yii2-date-range#30]
I used in my composer.json:
```
  "bower-asset/moment": "2.9.0"
```
You use too. In result I have two folder with moment lib. Can you move your moment to composer assets?

**Comment by kartik-v** [comment]
I understand. However in this case, it should not make a difference.

The moment.js is also included as a part of the [bootstrap-daterangepicker plugin](https://github.com/dangrossman/bootstrap-daterangepicker). So you will anyway have this file duplicated.

Note the reasons why I have not used bower for some of the plugins are:

- The widget is specifically tested for a version of the plugin and I do not want to auto update (I know you can control this through release versions - but it still feel this gives better control) - its just a couple of files to manage from the plugin
- More importantly I have additional code additions and enhancements over and above the plugin. For example this widget contains additional js files and locales to complement the plugin. In some cases I also have additional CSS and JS like in the Select2 widget. So I feel that maintaining all this in one assets folder gives better control.

Will figure out later how to manage this.

**Comment by fedemotta** [comment]
+1

I need to move bootstrap-daterangepicker to version 1.3.21 to make a fix for #34 but It is very difficult to update the js libraries this way. 

There are some changes in the js files added to work with this extension which should be handled outside the js library.

**Comment by kartik-v** [comment]
As I mentioned the extension is tested for a specific version and hence even if bower support is included - it will be for a specific JS version - and will need testing and update to upgrade the yii widget/extension as well.

BTW.. you can easily overwrite to point to your own assets using yii asset manager.
