### ISSUE TITLE
DateRangePicker cannot be found

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/yii2-date-range#39]
I have the DateRangePicker in my vendors folder and I have the use statement in my code and I am getting this error ...

exception 'yii\base\ErrorException' with message 'Class 'kartik\daterange\DateRangePicker' not found'

Any ideas why?

**Comment by JamesBarnsley** [comment]
If I only use the use statement it works but as soon as I use the widget the error appears. Class not found etc.

**Comment by kartik-v** [comment]
It seems to be an installation issue. Unfortunately cannot help much. You need to try removing vendors and reinstalling all packages via composer.
