### ISSUE TITLE
Provide 2 attributes to set start and end dates

### ISSUE THREAD

**Issue by evilito** [kartik-v/yii2-date-range#44]
Hello, to make this extension easy to use, please provide the ability to set 2 attributes. Currently, as I understand reading the documentation, you can only set one attribute from a model, and when you want to actually use the selected dates, you have to extract them for yourself using ugly string handling.

It would be way better if you could set 2 attributes, just as you can do with your other extension yii2-field-range:

```
echo FieldRange::widget([
    'form' => $form,
    'model' => $model,
    'label' => 'Enter date range',
    'attribute1' => 'begin_date',
    'attribute2' => 'end_date',
    'type' => FieldRange::INPUT_DATE,
]);
```

**Comment by kartik-v** [comment]
This is how the [source plugin has been designed](https://github.com/dangrossman/bootstrap-daterangepicker). It reads and writes data from a single field separated by string. So you may need to contact the plugin author if you need this changed.

**Comment by evilito** [comment]
Hello kartik,

Indeed, I was not referring to making two (visual) fields. I was referring to the internal handling of the start and end date, assigning them into 2 different attributes in a model.

In the [plugin documentation](http://www.daterangepicker.com/#options), there are actually two properties, startDate and endDate, which can be set and read independently. However I am afraid at this moment I lack the ability to integrate this functionality into your plugin by myself.

would you please consider reviewing this?

Relevant code examples:

```
//change the selected date range of that picker
$('#daterange').data('daterangepicker').setStartDate('2014-03-01');
$('#daterange').data('daterangepicker').setEndDate('2014-03-31');

//reading dates to log them
console.log(picker.startDate.format('YYYY-MM-DD'));
console.log(picker.endDate.format('YYYY-MM-DD'));
```
