### ISSUE TITLE
Cannot select end date earlier than current date

### ISSUE THREAD

**Issue by osCMattiFinn** [kartik-v/yii2-date-range#49]
The datepicker will not display a left arrow to select an end date earlier than the current date.

Deployed like this:

```php
$datepicker = DateRangePicker::widget([
'name'=>'DownloadHistorySearch[download_datetime]',
'convertFormat'=>true,
'pluginOptions'=>[
    'timePicker'=>false,
    'format'=>'d-m-Y',
	'opens'=>'left'
]            
]);
```

**Comment by kartik-v** [comment]
This is controlled by the plugin's inherent behavior. Update to the latest release where the plugin has enhancements where you will not face this.

**Comment by osCMattiFinn** [comment]
Thank you.  I have done this and all is good.
