### ISSUE TITLE
Using 'addon' property overrides populated format

### ISSUE THREAD

**Issue by losttheplot** [kartik-v/yii2-date-range#50]
The following deployment populates the form element with 'Y-m-d' as expected
```
<?= $form->field($model, 'date_published', [
               //'addon'=>['prepend'=>['content'=>'<i class="glyphicon glyphicon-calendar"></i>']],
                'options'=>['class'=>'form-group field-page-date_published']
            ])->widget(DateRangePicker::classname(), [
               // 'useWithAddon'=>true,
                'convertFormat'=>true,
                'pluginOptions'=>[
                    'timePicker'=>false,
                    'format'=>'Y-m-d',
                    'singleDatePicker'=>true,
                    'showDropdowns'=>true
                ] ]);
    ?>
```
...but if one uncomments the two lines to use the addon property, the form element is populated with 'Y-m-d - Y-m-d'. I realise that this is a DateRange picker, not a Date picker, but this still seems to me to look like a bug.

**Comment by kartik-v** [comment]
Cannot reproduce this. It seems to work fine - [check usage example 1 on demos page](http://demos.krajee.com/date-range#usage).

**Comment by losttheplot** [comment]
I think you misunderstand me. If you put the element into 'singleDatePicker' mode ('singleDatePicker'=>true), without the addon the date is populated 'Y-m-d' as expected. But if you then add the addon - still in 'singleDatePicker' mode, the date is populated with a range, as in 'Y-m-d - Y-m-d'. The details of the configuration are in my OP.

**Comment by kartik-v** [comment]
This is resolved now. Check the last 2 examples [in the usage section](http://demos.krajee.com/date-range#usage).
