### ISSUE TITLE
"Today" options is not working...

### ISSUE THREAD

**Issue by elim051** [kartik-v/yii2-date-range#54]
First , thanks for you good widget! 
I found a bug on selecting  "Today", http://demos.krajee.com/date-range, demo 3 
![image](https://cloud.githubusercontent.com/assets/6869709/12140822/c3d397da-b4a5-11e5-8734-c8e496cccbf2.png), this bug is occurred on other demos if the initial value is not set.
sorry for my english. hope you understand.

**Comment by DarthLegiON** [comment]
There are script in init() for this widget: 

```
        // Set `autoUpdateInput` to false for certain settings
        if (!$this->autoUpdateOnInit || $this->hideInput || $this->useWithAddon) {
            $this->pluginOptions['autoUpdateInput'] = false;
        }
```

You neet to set autoUpdateOnInit to true. If it is false, there will be no updating on choosing same option in dropdown and on initialization with empty value.

**Comment by dogrocker** [comment]
Thanks. @DarthLegiON

**Comment by uagrace** [comment]
I solved the problem with the "Today" in the following way:
```php
            [
                'attribute' => 'created_at',
                'format' => 'date',
                'headerOptions' => ['width' => '220'],
                'filter' => DateRangePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'date_range',
                    'presetDropdown' => true,
                    'convertFormat' => true,
                    'pluginOptions' => [
                        'locale' => [
                            'format' => 'd-m-Y',
                            'separator' => ' - ',
                            'cancelLabel' => 'clear'
                        ],
                    ],
                    'pluginEvents' => [
                        'apply.daterangepicker' => 'function(ev, picker) {
                            if($(this).val() == "") {
                                $(this).val(picker.startDate.format(picker.locale.format) + picker.locale.separator +
                                picker.endDate.format(picker.locale.format)).trigger("change");
                            }
                        }',
                        'show.daterangepicker' => 'function(ev, picker) {
                            picker.container.find(".ranges").off("mouseenter.daterangepicker", "li");
                            if($(this).val() == "") {
                                $(".ranges .active").removeClass("active");
                            }
                        }',
                        'cancel.daterangepicker' => 'function(ev, picker) {
                            if($(this).val() != "") {
                                $(this).val("").trigger("change");
                            }
                        }'
                    ]
                ]),
            ],
```

**Comment by juniogro10** [comment]
My solution,overwrite event in button ranges, lost translante.

Any idea for not lost translante?
` 'pluginOptions' => [
                                'ranges' => [
                                    Yii::t('kvdrp', "Today") => ["moment().utc().startOf('day')", "moment().utc().endOf('day')"]],`

**Comment by nageennayak11** [comment]
Not working any solution.

**Comment by maranqz** [comment]
Use next code if you need apply current date time on empty `input` when apply button down.
I test it on single datetime picker
```
'pluginEvents' => [
	'apply.daterangepicker' => 'function(ev, picker) {
        if($(this).val() == "") {
            picker.callback(picker.startDate.clone(), picker.endDate.clone(), picker.chosenLabel);
        }
    }',
]
```

**Comment by Anechka78** [comment]
You must add  in class DateRangePicker this - {$id}.find('.range-value').attr('placeholder', newValue);
`{$id}.on('apply.daterangepicker', function() {
        var drp = {$id}.data('{$this->pluginName}'), newValue = drp.startDate.format(drp.locale.format);
        if (!drp.singleDatePicker) {
            newValue += drp.locale.separator + drp.endDate.format(drp.locale.format);
        }

        if (newValue !== {$input}.val()) {
            {$input}.val(newValue).trigger('change');
        }

        {$id}.find('.range-value').attr('placeholder', newValue);
    });
`
