### ISSUE TITLE
DateRangePicker displays the wrong year data

### ISSUE THREAD

**Issue by kdjonua** [kartik-v/yii2-date-range#57]
My code is:
```
<?= $form->field($dateFilter, 'range', [
            'options' => [
                'style' => 'width: 200px',
            ]
        ])->widget(DateRangePicker::className(), [
            'model' => $dateFilter,
            'attribute' => 'range',
            'presetDropdown' => false,
            'initRangeExpr' => true,
            'pluginOptions' => [
                'format' => 'YYYY-MM-DD',
            ],
            'pluginEvents' => [
                "apply.daterangepicker" => "function() { $('#timeline-filterModel-form').submit(); }",
            ],
        ]) ?>
```

and I see the next daterangepicker:
![c](https://cloud.githubusercontent.com/assets/5098310/12235225/6154a522-b883-11e5-9b13-705eb1cb08bd.png)

(year as 000n)

**Comment by cicsolutions** [comment]
I too am experiencing similar behavior.  As in your screenshot, the dates next to the calendar icons are showing as "invalid date" for me too.

If I figure anything out, I'll let you know!

**Comment by cicsolutions** [comment]
I was able to fix this issue by setting the date format.  There may be a couple ways to do this, but I did it like this ...

	'pluginOptions' => [
		'locale' => ['format' => 'm/d/Y'],
	],

**Comment by kartik-v** [comment]
@kdjonua  you may want to read the plugin documentation for plugin options supported. There is no `format` property within `pluginOptions` that can be read by the plugin.

It is `pluginOptions['locale']['format']`.
