### ISSUE TITLE
DateRangePicker has problems with assets

### ISSUE THREAD

**Issue by Nasty-koskos** [kartik-v/yii2-date-range#74]
after init DateRangePicker Exception "An asset bundle that depends on 'yii\web\JqueryAsset' has a higher javascript file position configured than 'yii\web\JqueryAsset'." 

helped deleting a row **jsOptions** 

class LanguageAsset extends AssetBundle
{
_//    public $**jsOptions** = ['position' => \yii\web\View::POS_HEAD];_

    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->depends = array_merge($this->depends, ['\kartik\daterange\MomentAsset']);
        $this->setSourcePath(__DIR__ . '/assets');
        parent::init();
    }
}

**Comment by shershennm** [comment]
+
