### ISSUE TITLE
LanguageAsset doesn't get baseUrl

### ISSUE THREAD

**Issue by tiagovb** [kartik-v/yii2-date-range#76]
kartik\daterange\LanguageAsset does not get baseUrl, so when its loaded to the browser it appears like <script src="/js/locales/pt-BR.js"></script>

**Comment by mausspb** [comment]
I fix and great pull req.
https://github.com/kartik-v/yii2-date-range/pull/77/commits/788fd7ed794afd8fabfcfea7bbd26e80189cc729
