### ISSUE TITLE
asset load after asset jquery (error)

### ISSUE THREAD

**Issue by spiritdead** [kartik-v/yii2-date-range#79]
hi, when i use beginContent and endContent in the layouts, the asset of the daterangepicker load bad

i see the problem and in the depends need the dependency of the JqueryAsset

this is the fix for the file DateRangePickerAsset.php
```php
public $depends = [
        '\kartik\daterange\MomentAsset',
        'yii\web\JqueryAsset'
    ];
```

**Comment by spiritdead** [comment]
@kartik-v  plz, if can check this and make the update for download in the composer

regards

**Comment by kikimor** [comment]
Create release, please!
