### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by borison89** [kartik-v/yii2-date-range#81]
hi 
i have bug with DateRangePicker widget

i use him for filtering in gridview

```
                    [
                        'attribute' => 'TicketDateCreated',
                        'filter' => DateRangePicker::widget([
                            'model' => $searchModel,
                            'attribute' => 'TicketDateCreated',
                            'convertFormat' => true,
                            'presetDropdown'=>true,
                            'startAttribute' => 'TicketDateCreated_Date_From',
                            'endAttribute' => 'TicketDateCreated_Date_To',
                            'pluginOptions' => [
                                'locale' => [
                                    'format' => 'Y-m-d',
                                    'separator' => '/',
                                    'opens' => 'left'
                                ]
                            ]
                        ])
                    ],
```

if $TicketDateCreated_Date_From and $TicketDateCreated_Date_To is empty, then custom range is NAN and display Invalid date

I can add data in searchmodel and calendar would be worked, but i need empty this variables

```
if (empty($this->TicketDateCreated_Date_From) && empty($this->TicketDateCreated_Date_To)) {
            $this->TicketDateCreated_Date_From = date('Y-m-d', strtotime('-30 days'));/            $this->TicketDateCreated_Date_To = date('Y-m-d');
        }
```

![123](https://cloud.githubusercontent.com/assets/13521960/17176614/2c7479fc-5416-11e6-9077-6da6e4b2fce3.png)

**Comment by rommcr** [comment]
+1. The same problem.

**Comment by v0lume** [comment]
+1 same problem

**Comment by zmoddynamics** [comment]
+ same problem

**Comment by zmoddynamics** [comment]
I was able to resolve this by placing the 'format' property in 'locale' as shown below:

`'format' => ['date','php:m/d/yy h:i A'],
        'xlFormat' => "mmm\\-dd\\, \\-yyyy",
        'headerOptions' => ['class' => 'kv-sticky-column fit'],
        'contentOptions' => ['class' => 'kv-sticky-column fit'],
        'filterType'=>GridView::FILTER_DATE_RANGE,
        'filterWidgetOptions' => [
            'presetDropdown' => true,
            'hideInput'=>true,
            'useWithAddon'=>true,
            'convertFormat'=>true,
            'pluginOptions' => [
                'opens'=>'right',
                'locale' => [
                    'cancelLabel' => 'Clear',
                    'format' => 'Y-m-d',
                ]
                //'autoclose' => true,
            ],`

**Comment by gaginsgagins** [comment]
+1 
solve by zmoddynamics not working for me.

**Comment by kartik-v** [comment]
Yes this problem occurs because you have an invalid date format for the data that does not match the plugin's format.

**Comment by giovaANTO** [comment]
The solution provided by @zmoddynamics  doesn't work for me. 

@kartik-v  said that it's a problem that occurs because the format of the date doesn't match to the plugin format. so i've changed the option in the plugin

```
[
              'attribute' => 'date_field',
                'options' => ['class' => 'gridview-date-column'],
                'filter' => DateRangePicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'date_field',
                    'startAttribute' => 'date_start',
                    'endAttribute' => 'date_end',
                    'convertFormat'=>true,
                    'pluginOptions'=>[
                        'locale'=>['format' => 'd-m-Y'],
                    ],
                ]),
                'contentOptions'=>['style'=>'min-width: 200px;'] 
            ],
```

But as empty fields $date_start and $date_end how they can't have a correct data format because they have a date.

Someone have resolved this ? 

Thank you very much

**Comment by cipriancirstea** [comment]
I'm having the same problem.

**Comment by kakadanhem** [comment]
If you follow instruction, you would setup variable in Search model. In that case just add the default value as here: [Default attribute values](https://stackoverflow.com/questions/39314213/yii2-how-to-set-default-attribute-values-in-activerecord)

In my case:
`[['enrollDateStart'], 'default','value' => date('Y-m-d', strtotime('-30 days'))],
[['enrollDateStart'], 'default','value' => date('Y-m-d', strtotime('+30 days'))],`

However, I can choose Date only once, after it done loading, when I click on the picker it no longer show the date picker.

**Comment by esfahanweb** [comment]
just use:
`'pluginOptions' => [
                            'locale' => [
                                'format' => 'YYYY-MM-DD'
                            ]
                        ]`

**Comment by ThomiLee** [comment]
Is there a way to bypass this filter? I understood that I have to set default attribute values. Of course I could set start date to 1970-01-01 and end date to now. But isn't there an easier way to add an option "show all"?
Thanks for your help!

**Comment by is7** [comment]
In case default attributes values not set, 'startDate' and 'endDate' pluginOptions shouldn't be included in js daterangepicker. Now it {"startDate": null, "endDate": null}  

See the [issue 108](https://github.com/kartik-v/yii2-date-range/issues/108) to find a quick fix.
