### ISSUE TITLE
Same date

### ISSUE THREAD

**Issue by jcabanillas** [kartik-v/yii2-date-range#84]
Hello, when you select the same date (for both start and end), the "daterange field" remains empty.

**Comment by truth4oll** [comment]
+1 same problem

**Comment by CoderShawnZhang** [comment]
fix bug:
all code:
 updateElement: function() {
            if (this.element.is('input') && !this.singleDatePicker && this.autoUpdateInput) {
                this.element.val(this.startDate.format(this.locale.format) + this.locale.separator + this.endDate.format(this.locale.format));
                this.element.trigger('change');
            } else if (this.element.is('input') && this.autoUpdateInput) {
                this.element.val(this.startDate.format(this.locale.format));
                this.element.trigger('change');
            }else if(this.element.is('input') && !this.singleDatePicker && !this.autoUpdateInput){
                this.element.val(this.startDate.format(this.locale.format) + this.locale.separator + this.endDate.format(this.locale.format));
                this.element.trigger('change');
            }
        },

add code:
else if(this.element.is('input') && !this.singleDatePicker && !this.autoUpdateInput){
                this.element.val(this.startDate.format(this.locale.format) + this.locale.separator + this.endDate.format(this.locale.format));
                this.element.trigger('change');
            }

**Comment by kartik-v** [comment]
Cannot reproduce this... you can cross check in the usage section of the site.
