### ISSUE TITLE
Invalid date when setting both startAttribute and endAttribute

### ISSUE THREAD

**Issue by sebascar** [kartik-v/yii2-date-range#94]
This is an example code:

`echo DateRangePicker::widget([
            'name' => 'date_range',
            'attribute' => 'datetime_range',
            'startAttribute'  => 'startDate',
            'endAttribute' => 'endDate'
]);`

If **both** startAttribute and endAttribute are set then the picker goes nuts:
![alt text](https://content.screencast.com/users/scarmarketing/folders/Jing/media/7a942cde-3779-460a-a17e-3bb24d2ac85d/00000219.png)

**Comment by kartik-v** [comment]
Debug your code and your data. You should have a valid date value of the correct format set in your 2 range attributes. The format must match the plugin format set. Else your date range will get broken.

**Comment by Nemmo** [comment]
Same problem. It raises only if `startAttribute` and `endAttribute` setted and it concatenates two empty strings with separator

**Comment by giovaANTO** [comment]
@sebascar if you're using your widget without a model you can simply insert 'locale' to your pluginOptions configuration like this:

`'pluginOptions' => [
      'locale' => [
             'format' => 'd-m-Y'
       ],
 ],`

If then you use a model and startAttribute/endAttribute are propeties (field) of that model you can resolve this issue with the DateRangeBehavior.

`  
public $createTimeRange;
public $createTimeStart;
public $createTimeEnd;
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => DateRangeBehavior::className(),
                'attribute' => 'createTimeRange',
                'dateStartAttribute' => 'createTimeStart',
                'dateEndAttribute' => 'createTimeEnd',
                'dateStartFormat' => 'Y-m-d',
                'dateEndFormat' => 'Y-m-d'
            ],
        ];
    }`


this should resolve your issue
